<?php

namespace AppBundle\Controller;

use Sonata\AdminBundle\Controller\CRUDController as Controller;
use Symfony\Component\HttpFoundation\Response;
use Application\Sonata\UserBundle\Entity\TimeInterval;
class ScheduleController extends Controller
{
    public function render($view, array $parameters = array(), Response $response = null)
    {

        if ($parameters['action'] === 'list'){
            $em = $this->getDoctrine()->getManager();
            $timeIntervals = $em->getRepository('ApplicationSonataUserBundle:TimeInterval')->findAll();;
            $parameters['timeintervals'] = $timeIntervals;

            $weekdays = [
               '1' => 'Понедельник' ,
               '2' => 'Вторник' ,
               '3' => 'Среда' ,
               '4' => 'Четверг' ,
               '5' => 'Пятница' ,
               '6' => 'Суббота',
               '0' => 'Воскресенье'
            ];
            $parameters['weekdays'] = $weekdays;
        }
        return parent::render($view, $parameters, $response); // TODO: Change the autogenerated stub
    }
}