imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/admin.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
                    json: Sonata\Doctrine\Types\JsonType
    orm:
        #auto_generate_proxy_classes: "%kernel.debug%"
            entity_managers:
              default:
                mappings:  
                  ApplicationSonataUserBundle: ~                
                  SonataUserBundle: ~
                  FOSUserBundle: ~
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
#
sonata_admin:
    title: Администратор
    title_logo: bundles/app/images/logo_title.png
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: AppBundle::standard_layout.html.twig
        edit: AppBundle:CRUD:base_edit.html.twig
    show_mosaic_button: false
    dashboard:
        groups:
            pupil_group:
                label: Учащиеся
                items:
                    - app.admin.pupil
                    - app.admin.parent
                    - app.admin.group
                    - app.admin.journal
                    - app.admin.lesson
            employee_group:
                label: Сотрудники
                items:
                    - admin.teacher
                    - admin.metodist
            subject_group:
                on_top: true
                label: Предметы
                items:
                    - admin.subject
            message_group:
                on_top: true
                label: Сообщения
                items:
                    - admin.message
            room_group:
                on_top: true
                label: Аудитории
                items:
                    - admin.classroom
            time_group:
                on_top: true
                label: Интервалы времени
                items:
                    - admin.timeinterval
            schedule_group:
                on_top: true
                label: Расписание
                items:
                    - admin.schedule
sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    admin:                  # Admin Classes
            user:
                class: AppBundle\Admin\UserAdmin
                #Sonata\UserBundle\Admin\Entity\UserAdmin
                controller:     SonataAdminBundle:CRUD
                translation:    SonataUserBundle
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        #...
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

sonata_intl:
    timezone:
        locales:
            ru: Europe/Minsk
        detectors:
            - sonata.intl.timezone_detector.user
            - sonata.intl.timezone_detector.locale
        default: Europe/Minsk

fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
       group_class: Application\Sonata\UserBundle\Entity\Group
       group_manager: sonata.user.orm.group_manager 
    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

fos_rest:
    body_listener: true
    view:
      view_response_listener: true
    serializer:
        serialize_null: true
    body_converter:
        enabled: true
    format_listener:
        rules:
            - { path: '^/api',  priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }

jms_serializer:
    property_naming:
        separator:  _
        lower_case: true

    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/config/serializer/FosUserBundle"
            Application:
                namespace_prefix: "Application\\Sonata\\UserBundle"
                path: "%kernel.root_dir%/config/serializer/Application"
        auto_detection: true