ajax_group:
    path: /admin/my-post/{groupId}
    defaults: { _controller: AppBundle:ViewSchedule:ajaxGroups }
    options:
      expose: true

app_teacher_cabinet:
    path: /teacher/{id}/cabinet
    defaults: {_controller: AppBundle:Index:teacher}
    requirements:
        id: '\d+'

app_pupul_cabinet:
    path: /pupil/{id}/cabinet
    defaults: {_controller: AppBundle:Index:pupil}
    requirements:
        id: '\d+'

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

users:
    type:     rest
    resource: "@AppBundle/Controller/PupilCabinetController.php"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

sonata_user_security:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_admin_resetting:
    resource: '@ApplicationSonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting


