# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_METODIST:
            - ROLE_APP_ADMIN_PUPIL_ALL
            - ROLE_APP_ADMIN_PARENT_ALL
            - ROLE_APP_ADMIN_GROUP_ALL
            - ROLE_APP_ADMIN_JOURNAL_ALL
            - ROLE_APP_ADMIN_LESSON_ALL
            - ROLE_ADMIN_TEACHER_ALL
            - ROLE_ADMIN_METODIST_ALL
            - ROLE_ADMIN_SUBJECT_ALL
            - ROLE_ADMIN_MESSAGE_ALL
            - ROLE_ADMIN_CLASSROOM_ALL
            - ROLE_ADMIN_TIMEINTERVAL_ALL
            - ROLE_ADMIN_SCHEDULE_ALL
        ROLE_ADMIN:       [ROLE_STAFF, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented
    access_control:
            # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be accessed without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_METODIST] }
        - { path: ^/teacher/, role: [ROLE_TEACHER, ROLE_ADMIN] }
        - { path: ^/pupil/, role: [ROLE_PARENT, ROLE_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    acl:
        connection: default

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            #id: fos_user.user_manager
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:            .*
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
                success_handler: app_success_handler
            logout:
                path:           /logout
                target:         /login
            anonymous:          true