# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#  sonata.admin.user:
#    class: AppBundle\Admin\UserAdmin
#    tags:
#        - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
#    arguments:
#        - ~
#        - Application\Sonata\UserBundle\Entity\User
#        - ~
#    calls:
#        - [ setTranslationDomain, [AppBundle]]
    app.admin.pupil:
        class: AppBundle\Admin\PupilAdmin
        arguments: [~, Application\Sonata\UserBundle\Entity\UserPupil, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'iTeen', label: 'Учащиеся' }
    app.admin.parent:
            class: AppBundle\Admin\ParentAdmin
            arguments: [~, Application\Sonata\UserBundle\Entity\UserParent, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: 'iTeen', label: 'Родители' }
    app.admin.group:
                class: AppBundle\Admin\GroupAdmin
                arguments: [~, Application\Sonata\UserBundle\Entity\GroupIteen, ~]
                tags:
                    - { name: sonata.admin, manager_type: orm, group: 'iTeen', label: 'Группы' }
    app.admin.group_pupil:
                    class: AppBundle\Admin\PupilGroupAssociationsAdmin
                    arguments: [~, Application\Sonata\UserBundle\Entity\PupilGroupAssociations, ~]
                    tags:
                        - { name: sonata.admin, manager_type: orm }
