# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#  sonata.admin.user:
#    class: AppBundle\Admin\UserAdmin
#    tags:
#        - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
#    arguments:
#        - ~
#        - Application\Sonata\UserBundle\Entity\User
#        - ~
#    calls:
#        - [ setTranslationDomain, [AppBundle]]
    app.admin.pupil:
        class: AppBundle\Admin\PupilAdmin
        arguments: [~, Application\Sonata\UserBundle\Entity\UserPupil, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Temp, label: 'Учащиеся' }
