# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#  sonata.admin.user:
#    class: AppBundle\Admin\UserAdmin
#    tags:
#        - { name: sonata.admin, manager_type: orm, group: "User", label: "User" }
#    arguments:
#        - ~
#        - Application\Sonata\UserBundle\Entity\User
#        - ~
#    calls:
#        - [ setTranslationDomain, [AppBundle]]
    app.admin.pupil:
        class: AppBundle\Admin\PupilAdmin
        arguments:
            - null
            - Application\Sonata\UserBundle\Entity\UserPupil
            - AppBundle:Main
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Учащиеся', label: 'Учащиеся' }

    app.admin.parent:
        class: AppBundle\Admin\ParentAdmin
        arguments:
            - null
            - Application\Sonata\UserBundle\Entity\UserParent
            - AppBundle:Main
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Учащиеся', label: 'Родители' }

    app.admin.group:
        class: AppBundle\Admin\GroupAdmin
        arguments:
            - null
            - Application\Sonata\UserBundle\Entity\GroupIteen
            - AppBundle:Group
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Учащиеся', label: 'Группы' }

    app.admin.journal:
        class: AppBundle\Admin\JournalAdmin
        arguments:
            - null
            - Application\Sonata\UserBundle\Entity\GroupIteen
            - AppBundle:Journal
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Учащиеся', label: 'Журналы' }
        calls:
            - [addChild, ['@admin.subject']]

    app.admin.lesson:
        class: AppBundle\Admin\LessonAdmin
        arguments:
            - null
            - Application\Sonata\UserBundle\Entity\Lesson
            - AppBundle:Lesson
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Учащиеся', label: 'Уроки' }
        calls:
            - [ setTemplate, [createLesson, AppBundle:LessonAdmin:lesson_create.html.twig] ]

    app_success_handler:
        class: AppBundle\Services\AuthenticationHandler
        arguments: ['@service_container']