services:
     admin.teacher:
          class: AppBundle\Admin\TeacherAdmin
          arguments: [~, Application\Sonata\UserBundle\Entity\UserTeacher, ~]
          tags:
             - { name: sonata.admin, manager_type: orm, group: Сотрудники, label: Преподаватели }
          calls:
             - [ setTranslationDomain, [AppBundle]]
             - [ setTemplate, [list, AppBundle:TeacherAdmin:base_list.html.twig]]
     admin.metodist:
           class: AppBundle\Admin\MetodistAdmin
           arguments: [~, Application\Sonata\UserBundle\Entity\UserMetodist, ~]
           tags:
              - { name: sonata.admin, manager_type: orm, group: Сотрудники, label: Методисты }
           calls:
              - [ setTranslationDomain, [AppBundle]]
              - [ setTemplate, [list, AppBundle:MetodistAdmin:base_list.html.twig]]
     admin.subject:
            class: AppBundle\Admin\SubjectAdmin
            arguments: [~, Application\Sonata\UserBundle\Entity\Subject, ~]
            tags:
               - { name: sonata.admin, manager_type: orm, group: Предметы, on_top: true }
            calls:
               - [ setTranslationDomain, [AppBundle]]
     admin.classroom:
                class: AppBundle\Admin\ClassroomAdmin
                arguments: [~, Application\Sonata\UserBundle\Entity\Classroom, ~]
                tags:
                   - { name: sonata.admin, manager_type: orm, group: Аудитории , on_top: true }
                calls:
                   - [ setTemplate, [list, AppBundle:ClassroomAdmin:classroom_list.html.twig]]
     admin.timeinterval:
                class: AppBundle\Admin\TimeIntervalAdmin
                arguments: [~, Application\Sonata\UserBundle\Entity\TimeInterval, ~]
                tags:
                   - { name: sonata.admin, manager_type: orm, group: Интервалы времени , on_top: true, show_in_dashboard: false}
     admin.schedule:
                class: AppBundle\Admin\ScheduleAdmin
                arguments: [~, Application\Sonata\UserBundle\Entity\Schedule, AppBundle:Schedule]
                tags:
                   - { name: sonata.admin, manager_type: orm, group: Расписание , on_top: true, show_in_dashboard: true}
                calls:
                  - [setTemplate, [list, AppBundle:ScheduleAdmin:schedule_list.html.twig]]
                  - [setTemplate, [edit, AppBundle:ScheduleAdmin:schedule_edit.html.twig]]
     app.admin.viewschedule:
                class: AppBundle\Admin\ViewScheduleAdmin
                arguments: [~, ~, AppBundle:ViewSchedule]
                tags:
                    - { name: sonata.admin, manager_type: orm, group: Таблица Расписания, on_top: true, show_in_dashboard: false}


