services:
     admin.teacher:
          class: AppBundle\Admin\TeacherAdmin
          arguments: [~, Application\Sonata\UserBundle\Entity\UserTeacher, ~]
          tags:
             - { name: sonata.admin, manager_type: orm, group: Сотрудники, label: Преподаватели }
          calls:
             - [ setTranslationDomain, [AppBundle]]
             - [ setTemplate, [list, AppBundle:TeacherAdmin:base_list.html.twig]]
     admin.metodist:
           class: AppBundle\Admin\MetodistAdmin
           arguments: [~, Application\Sonata\UserBundle\Entity\UserMetodist, ~]
           tags:
              - { name: sonata.admin, manager_type: orm, group: Сотрудники, label: Методисты }
           calls:
              - [ setTranslationDomain, [AppBundle]]
              - [ setTemplate, [list, AppBundle:MetodistAdmin:base_list.html.twig]]
     admin.subject:
            class: AppBundle\Admin\SubjectAdmin
            arguments: [~, Application\Sonata\UserBundle\Entity\Subject, ~]
            tags:
               - { name: sonata.admin, manager_type: orm, group: Предметы, on_top: true }
            calls:
               - [ setTranslationDomain, [AppBundle]]
     admin.classroom:
                class: AppBundle\Admin\ClassroomAdmin
                arguments: [~, Application\Sonata\UserBundle\Entity\Classroom, ~]
                tags:
                   - { name: sonata.admin, manager_type: orm, group: Аудитории , on_top: true }
                calls:
                   - [ setTemplate, [list, AppBundle:ClassroomAdmin:classroom_list.html.twig]]
