<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
abstract class User extends BaseUser
{
    // TODO: Константы класса
    // TODO: добавить свойства: отчество, адрес, комментарий

    /**
     * @var int $id
     */
    //protected $id;

    /**
     * @var
     */
    protected $patronymic;

    /**
     * @var
     */
    protected $comment;

    /**
     * @return mixed
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * @param mixed $comment
     */
    public function setComment($comment)
    {
        $this->comment = $comment;
    }
    /**
     * @return mixed
     */
    public function getPatronymic()
    {
        return $this->patronymic;
    }

    /**
     * @param mixed $patronymic
     */
    public function setPatronymic($patronymic)
    {
        $this->patronymic = $patronymic;
    }

    /**
     * Get id
     *
     * @return int $id
     */

    public function getId()
    {
        return $this->id;
    }

    public function __toString()
    {
        $string = $this->getFirstname().' '.$this->getLastname();
        if (!$string) {
            $string = $this->getUsername();
        }

        //return $string ?: '';
        return $string;
    }
}
