<?php

namespace Application\Sonata\UserBundle\Repository;

/**
 * AuditoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuditoriRepository extends \Doctrine\ORM\EntityRepository
{
}
