<?php

namespace Application\Sonata\UserBundle\Repository;

/**
 * ClassroomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDistinctTeachers()
    {
        $teachers = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('u')
            ->from($this->_entityName, 'u')
            ->groupBy('u.teacher')
            ->getQuery()->getResult();
        $schedule = $this->findAll();
         foreach ($teachers as $oneTeachers){
             for( $weekday = 0 ; $weekday <= 6 ; $weekday++ ){
                 foreach ($schedule as $lesson){
                     $nameTeacherLesson = $lesson->getTeacher()->getFullname();
                     $nameTeacher = $oneTeachers->getTeacher()->getFullname();
                     $lessonTimeintervalId = $lesson->getTimeinterval()->getId();
                     if (($nameTeacherLesson === $nameTeacher) and ($lesson->getWeekday() === $weekday ) ){
                         $sortSchedule[$nameTeacher][$weekday][$lessonTimeintervalId] = $lesson;
                     }
                 }

             }
         }
        return $sortSchedule;
    }

    public function getDistinctGroups()
    {
        $groups = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('u')
            ->from('ApplicationSonataUserBundle:Schedule', 'u')
            ->groupBy('u.group')
            ->getQuery()->getResult();

        return $groups;
    }

    public function getDistinctClassrooms()
    {
        $classrooms =  $this->getEntityManager()
            ->createQueryBuilder()
            ->select('u')
            ->from('ApplicationSonataUserBundle:Schedule', 'u')
            ->groupBy('u.classroom')
            ->getQuery()->getResult();

        return $classrooms;
    }
}
