<?php

namespace Application\Sonata\UserBundle\Repository;

/**
 * TimeForClassroomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeForClassroomRepository extends \Doctrine\ORM\EntityRepository
{
}
